### ISSUE TITLE
Kernel 3.3.8-1?

### ISSUE THREAD

**Issue by Zodiac-69** [8devices/packages#1]
Hi All

Just seen that with the new V2.2, that the Kernel has been updated to 3.3.8-1...

I see that Luci still indicate 3.3.8, but if you look at under "System - Software" i see kernel 3.3.8-1-edeecade6a9a64f967fa425aed2da53f

I update to the latest and as far as i understand my Carambola is no on Kernel 3.3.8-1, as per my previous post.

But, i still get this error...
Installing kmod-rotary-gpio-custom (3.3.8-1) to root...
Downloading http://downloads.openwrt.org/snapshots/ ... ramips.ipk.

Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-rotary-gpio-custom:
- kernel (= 3.3.8-1-efc6295fa82a478a46d3197099661a6a) \* kernel (= 3.3.8-1-efc6295fa82a478a46d3197099661a6a) \* kernel (= 3.3.8-1-efc6295fa82a478a46d3197099661a6a) *
- opkg_install_cmd: Cannot install package kmod-rotary-gpio-custom.

Does this mean that i am NOT on Kernel 3.3.8-1?

Z69

**Comment by 8devices** [comment]
Hi,

I see that you are downloading packages from  http://downloads.openwrt.org/snapshots/ ... 
Can you please try http://pkg.8devices.com/v2.2/carambola/packages/ instead ? Error
you see it tells that kernel version is incompatible with a package.

**Comment by Zodiac-69** [comment]
I tried that as well with the same results...

Installing kmod-rotary-gpio-custom (3.3.8-1) to root...
Downloading http://pkg.8devices.com/v2.2/carambola/packages//kmod-rotary-gpio-custom_3.3.8-1_ramips.ipk.

```
                Collected errors:
```
- satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-rotary-gpio-custom:
-  kernel (= 3.3.8-1-8d3998a22ef3a06fbe475ba3ea877e97) \*   kernel (= 3.3.8-1-8d3998a22ef3a06fbe475ba3ea877e97) \*   kernel (= 3.3.8-1-8d3998a22ef3a06fbe475ba3ea877e97) \* 
- opkg_install_cmd: Cannot install package kmod-rotary-gpio-custom.

Z69

**Comment by 8devices** [comment]
Can you send me an output of 'opkg list | grep kernel' command ?

The output should look like this:
root@OpenWrt:/# opkg list | grep kernel
kernel - 3.3.8-1-8d3998a22ef3a06fbe475ba3ea877e97

If kernel package SHA1 does not match - it means that sysupgrade
is needed in order to use packages from pkg.8devices.com.

**Comment by Zodiac-69** [comment]
Here is the output as requested:

root@OpenWrt:~# opkg list | grep kernel
 You must have enabled the ALSA support in the kernel.
 purpose: tell Linux kernel what to enforce. In essence it is a udev
 helper for communication between the kernel and userspace. You only
kernel - 3.3.8-1-edeecade6a9a64f967fa425aed2da53f
kmod-ipt-conntrack - 3.3.8-1 - Netfilter (IPv4) kernel modules for connection tracking
kmod-ipt-conntrack-extra - 3.3.8-1 - Netfilter (IPv4) extra kernel modules for connection tracking
kmod-ipt-core - 3.3.8-1 - Netfilter core kernel modules
kmod-ipt-filter - 3.3.8-1 - Netfilter (IPv4) kernel modules for packet content inspection
kmod-ipt-nat - 3.3.8-1 - Netfilter (IPv4) kernel modules for basic NAT targets
kmod-ipt-nat-extra - 3.3.8-1 - Netfilter (IPv4) kernel modules for extra NAT targets
kmod-sched - 3.3.8-1 - Extra kernel schedulers modules for IP traffic
kmod-sched-core - 3.3.8-1 - Core kernel scheduler support for IP traffic
wprobe-export - 1-1 - wprobe-export uses the wprobe kernel module to export
wprobe-util - 1-1 - wprobe-util uses the wprobe kernel module to query
root@OpenWrt:~#

**Comment by 8devices** [comment]
kernel - 3.3.8-1-edeecade6a9a64f967fa425aed2da53f has a different SHA1 tag.
It means you need to upgrade your kernel/rootfs combo on PCB. Try upgrading
using this image:

http://pkg.8devices.com/v2.2/carambola/openwrt-ramips-rt305x-carambola-squashfs-sysupgrade.bin

It should help.

**Comment by Zodiac-69** [comment]
I see you updated the package, thank you, it now works.

**Comment by 8devices** [comment]
It looks like problem solved. :)
