### ISSUE TITLE
GPIO control packages are missing

### ISSUE THREAD

**Issue by Lukse** [8devices/packages#11]
Hello, 

gpioctl is missing from package list. Would like to see this option enabled in build environment by default. Thank you!
## 

Saulius

**Comment by valinskas** [comment]
Since 8devices/carambola@19c78e190526b81e2c2fca6a53fcd141a8dd03b4 'gpioctl' has been removed.
No alternative was mention either. I can suggest to use /sys/class/gpio/\* entries to control GPIO:

http://squidge.sourceforge.net/gpio/
http://www.kernel.org/doc/Documentation/gpio.txt
