### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by Lukse** [8devices/packages#15]
Please enable these packages in package repository:

usbip
usbip-client
usbip-server

Thank you!

**Comment by valinskas** [comment]
In progress.

**Comment by valinskas** [comment]
Kernel configuration has changed, see kmod options. So it most likely requires
kernel upgrade too. Anyway  - requested packages built and uploaded. Good luck,

```
CONFIG_PACKAGE_usbip=m
CONFIG_PACKAGE_usbip-client=m
CONFIG_PACKAGE_usbip-server=m
CONFIG_PACKAGE_libwrap=m
CONFIG_PACKAGE_kmod-usbip=m
CONFIG_PACKAGE_kmod-usbip-client=m
CONFIG_PACKAGE_kmod-usbip-server=m
```

**Comment by Lukse** [comment]
Thank you very much! There is usage example and how to configure Carambola/PC: http://www.8devices.com/wiki_carambola/doku.php/using_usbip_with_carambola
