### ISSUE TITLE
"OPKG update" not running

### ISSUE THREAD

**Issue by emmerichoma** [8devices/packages#17]
OPKG is not running on my Carambola, obviously because the Carambola is not able to access the 8Devicespackages pages, this seems to be because the resolv.conf file does not include a nameserver 8.8.8.8

Whenever I include the statement for 8.8.8.8 and restart the network then this entry is deleted from config. So I am running in circles and need desperately help

Thanks in advance

is there an e-mail address for direct contact with 8Devices???

**Comment by Lukse** [comment]
First of all it's not OPKG fault. It's your network configuration.

There are some questions that might help answering your problem:

How do you connect to internet? Is it static configuration or dhcp configuration? Do you have router? Do you connect over WiFi or LAN or WAN? Can you ping external ip addresses like google.com? Please provide complete configuration files you have changed. 

There is manual on OpenWrt, which could help you. Please study it here: http://wiki.openwrt.org/doc/uci/network

**Comment by emmerichoma** [comment]
Hello Saulius,

I very much appreciate your feedback, which has helped solve the problem. I had not thought of an issue with my network. I pinged and it did not work.

I have then checked the setup of the network and found an entry "this is the only DHCP server in the LAN", which was not the case since my router was acting as DHCP. I took off that switch and applied. That resolved the issue. So, you were correct stating that it was not the OPKG.

As you can see I am not a Linux expert, however, I am learning, I love the Carambola and will eventually get it going.

Again, many thanks and best regards,

Emmerich Christiansen

Am 21.01.2013 um 16:50 schrieb Saulius Lukse notifications@github.com:

**Comment by valinskas** [comment]
Now that issue was resolved, closing.
