### ISSUE TITLE
uhttpd: https fails with current repository (v2.3-r4)

### ISSUE THREAD

**Issue by fwt-dot-fr** [8devices/packages#20]
i try httpd with TLS mode
when i run httpd with TLS enable:

 /usr/sbin/uhttpd -f -h /www -r CARAMBOLA -x /cgi-bin -l /lua -L /root/test.lua -t 60 -T 30 -A 1 -n 3 -R -p 0.0.0.0:80 -C /etc/uhttpd.crt -K /etc/uhttpd.key -s 0.0.0.0:443
IO: FD(4) added to uloop
Notice: TLS support not compiled, ignoring -C
Notice: TLS support not compiled, ignoring -K
IO: FD(5) added to uloop

following https://dev.openwrt.org/ticket/12869 i think that the packages
 libustream-cyassl........................... ustream SSL Library (cyassl)
 libustream-openssl......................... ustream SSL Library (openssl)

are missing in the repository.

Could you add then ?

package: /package/libs/ustream-ssl

Thanks

**Comment by valinskas** [comment]
Hi, 

It works for me after:

```
# opkg update
# opkg install px5g uhttpd-mod-tls  uhttpd-mod-ubus 
```

Additional  package 'libcyassl' is installed as dependency on uhttpd-mod-tls

```
# reboot 
```

or 

```
# /etc/init.d/lucid stop
# /etc/init.d/uhttpd start
```

TLS works as you can see from curl output below:

```
`--> curl -vk https://192.168.100.239/ 
* About to connect() to 192.168.100.239 port 443 (#0)
*   Trying 192.168.100.239...
* connected
* Connected to 192.168.100.239 (192.168.100.239) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*        subject: C=DE; ST=Berlin; L=Berlin; CN=OpenWrt
*        start date: 2012-10
*        expire date: 2014-10
*        common name: OpenWrt (does not match '192.168.100.239')
*        issuer: C=DE; S
*        SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> User-Agent: curl/7.27.0
> Host: 192.168.100.239
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Connection: close
< ETag: "f4-1a3-507892d9"
< Last-Modified: Fri, 12 Oct 2012 21:59:53 GMT
< Date: Fri, 12 Oct 2012 22:30:35 GMT
< Content-Type: text/html
< Content-Length: 419
< Transfer-Encoding: chunked
< 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="refresh" content="0; URL=/cgi-bin/luci" />
</head>
<body style="background-color: black">
<a style="color: white; text-decoration: none" href="/cgi-bin/luci">LuCI - Lua Configuration Interface</a>
</body>
</html>
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

**Comment by fwt-dot-fr** [comment]
Hi,

I didn’t do like this

I build the image from the repository

VERSIONTOINSTALL="v2.3-rc4"

DestDir="gittrunk-$VERSIONTOINSTALL"

cd $DestDir

git pull

cd feeds/packages

git pull

cd ../..

./scripts/feeds update -a

./scripts/feeds install -a

make menuconfig

Network  --->Web Servers/Proxies  --->

<_> uhttpd........................ uHTTPd - tiny, single threaded HTTP server
[_] Build with debug messages
<_> uhttpd-mod-lua... uHTTPd - tiny, single threaded HTTP server (Lua plugin)
<_> uhttpd-mod-tls... uHTTPd - tiny, single threaded HTTP server (TLS plugin)
       TLS Provider (CyaSSL)  --->(X) CyaSSL

<*> uhttpd-mod-ubus. uHTTPd - tiny, single threaded HTTP server (ubus plugin)

make world V=99

Thierry Museux
France Wireless Technologies
 http://www.fwt.fr/ www.fwt.fr
msn:  mailto:tm@fwt.fr tm@fwt.fr
Tel: + 33 (0) 1 41 08 70 78

De : Žilvinas Valinskas [mailto:notifications@github.com] 
Envoyé : mardi 26 février 2013 13:19
À : 8devices/packages
Cc : fwt-dot-fr
Objet : Re: [packages] uhttpd: https fails with current repository (v2.3-r4) (#20)

Hi, 

It works for me after:

# opkg update

# opkg install px5g uhttpd-mod-tls  uhttpd-mod-ubus

Additional package 'libcyassl' is installed as dependency on uhttpd-mod-tls

# reboot

or 

# /etc/init.d/lucid stop

# /etc/init.d/uhttpd start

TLS works as you can see from curl output below:

`--> curl -vk https://192.168.100.239/ 
- About to connect() to 192.168.100.239 port 443 (#0)
-   Trying 192.168.100.239...
- connected
- Connected to 192.168.100.239 (192.168.100.239) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using AES256-SHA
- Server certificate:
-        subject: C=DE; ST=Berlin; L=Berlin; CN=OpenWrt
-        start date: 2012-10
-        expire date: 2014-10
-        common name: OpenWrt (does not match '192.168.100.239')
-        issuer: C=DE; S
-        SSL certificate verify result: self signed certificate (18), continuing anyway.
  > GET / HTTP/1.1
  > User-Agent: curl/7.27.0
  > Host: 192.168.100.239
  > Accept: _/_
  > 
- additional stuff not fine transfer.c:1037: 0 0
- HTTP 1.1 or later with persistent connection, pipelining supported
  < HTTP/1.1 200 OK
  < Connection: close
  < ETag: "f4-1a3-507892d9"
  < Last-Modified: Fri, 12 Oct 2012 21:59:53 GMT
  < Date: Fri, 12 Oct 2012 22:30:35 GMT
  < Content-Type: text/html
  < Content-Length: 419
  < Transfer-Encoding: chunked
  < 
  <?xml version="1.0" encoding="utf-8"?>
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="refresh" content="0; URL=/cgi-bin/luci" />
  </head>
  <body style="background-color: black">
  <a style="color: white; text-decoration: none" href="/cgi-bin/luci">LuCI - Lua Configuration Interface</a>
  </body>
  </html>
- Closing connection #0
- SSLv3, TLS alert, Client hello (1):

**Comment by valinskas** [comment]
Hi,
it's a known problem, see 8devices/carambola#14.  It will go away when  8devices/carambola 
repository catches up with upstream (planning to do that on March). Meantime you can do like
this:

Update feeds.conf.default from:

```
src-git packages git://github.com/8devices/packages.git
```

To

```
src-git packages git://github.com/8devices/packages.git;carambola/v2.3
```

'';carambola/v2.3'; is important part.  it checks out carambola/v2.3 branch
from 8devices/packages repository so it matches 8devices/carambola
branch.

I hope it will allow to build TLS related packages successfully.
