### ISSUE TITLE
package request: nfs-utils

### ISSUE THREAD

**Issue by hutorny** [8devices/packages#23]
Hi,

As per OpenWrt wiki http://wiki.openwrt.org/doc/howto/nfs.client
nfs-utils is a prerequisite for NFS4 client, it provides updated mount.nfs command that allows mounting nfs4 volumes

In seems this package is not available in the carambola repo:

> Unknown package 'nfs-utils'.
> Collected errors:
> - opkg_install_cmd: Cannot install package nfs-utils.

**Comment by valinskas** [comment]
Compiling in progress. Will let you know when packages are built and uploaded.

```
    CONFIG_PACKAGE_nfs-kernel-server=m
    CONFIG_PACKAGE_nfs-kernel-server-utils=m
    CONFIG_PACKAGE_portmap=m
    CONFIG_PACKAGE_libblkid=m
    CONFIG_PACKAGE_libevent=m
    CONFIG_PACKAGE_nfs-utils=m
```

**Comment by valinskas** [comment]
Done compiling, pkgs uploaded to a server.

Please run:

```
# opkg update
# opkg install nfs-utils
```

**Comment by hutorny** [comment]
<pre>
root@ca:/# opkg update
Downloading http://pkg.8devices.com/v2.4/carambola2/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/snapshots.
root@ca:/# opkg install nfs-utils
Unknown package 'nfs-utils'.
Collected errors:
 * opkg_install_cmd: Cannot install package nfs-utils.
</pre>

**Comment by valinskas** [comment]
It looks to me that you are using "Carambola2" - Atheros AR9331 based SoC. I have compiled packages
for Carambola - Ralink RT3052 based SoC. Each boards have different repositories too ... Oh it's confusing.

I will make sure that Carambola2 also have nfs-utils and related packages enabled.

**Comment by hutorny** [comment]
Yes, that's right, sorry for not mentioning it in the original post

**Comment by valinskas** [comment]
No problem ;) I will let you know when packages are compiled/uploaded.

**Comment by adarius** [comment]
available on repository.

**Comment by hutorny** [comment]
Thanks
